#!/usr/bin/env python3
"""Resolve a curated track plan, validate it, and (optionally) create the
YouTube Music playlist.

This script does NOT choose tracks -- that's done by Claude during curation.
Its job is mechanical: resolve queries to real tracks, enforce whatever
protocol rules apply (segment timing, artist diversity, vocal policy),
report a timeline, and create/sync the playlist once approved.

All protocol-specific policy (segment names + targets, tolerance, artist
diversity caps, vocal-detection mode, total-length boundary) comes from an
optional --protocol JSON config -- see references/protocol-config.md for
the schema. Without --protocol, the plan is built as an unconstrained flat
playlist: any phase/segment names are accepted, no timing or diversity
checks run, and vocal detection is off.

No-reuse tracking (never adding a track already used in a prior playlist,
or one permanently banned) is opt-in -- omit both --exclude-dir and a
protocol's "exclude_dir" for a one-off playlist with no such tracking. Turn
it on when the user asks not to repeat tracks across playlists, or bake a
fixed "exclude_dir" into a --protocol so a consumer never has to pass
--exclude-dir itself (e.g. ketamine-infusion-playlist always does this).
--exclude-dir on the command line overrides a protocol's "exclude_dir" if
both are given. See references/exclude-lists.md.

Plan file format (JSON):
{
  "title": "My Playlist -- 2026-07-14",
  "phases": [
    {"name": "Build", "tracks": ["Artist - Title", ...]},
    {"name": "Peak", "tracks": [...]},
    {"name": "Wind-down", "tracks": [...]}
  ],
  "vocal_ok": ["Artist - Title"]
}
"phases" and "segments" are accepted interchangeably as the top-level key.
Segment names must match a --protocol's segments, if one was given.
"target_seconds" on a phase entry overrides the protocol's target for that
segment.

Usage:
    python3 build_playlist.py --list-playlists
    python3 build_playlist.py --protocol protocol.json --plan plan.json --dry-run
    python3 build_playlist.py --protocol protocol.json --plan plan.json --dry-run --no-lyrics-check
    python3 build_playlist.py --protocol protocol.json --plan plan.json --dry-run --no-audio-check
    python3 build_playlist.py --protocol protocol.json --plan plan.json
    python3 build_playlist.py --show PLxxxx
    python3 build_playlist.py --protocol protocol.json --sync PLxxxx --plan plan.json --dry-run
    python3 build_playlist.py --protocol protocol.json --sync PLxxxx --plan plan.json

    # Opt-in no-reuse tracking (add --exclude-dir DIR to any of the above too,
    # or bake "exclude_dir" into --protocol and drop --exclude-dir entirely):
    python3 build_playlist.py --exclude-dir DIR --add-exclude PLxxxx PLyyyy
    python3 build_playlist.py --exclude-dir DIR --remove-exclude PLxxxx
    python3 build_playlist.py --exclude-dir DIR --add-exclude-track "Artist - Title" [...]
    python3 build_playlist.py --exclude-dir DIR --list-exclude-tracks
    python3 build_playlist.py --exclude-dir DIR --finalize PLxxxx

    # Unavailable (removed/blocked) tracks:
    python3 build_playlist.py --check-availability PLxxxx [PLyyyy ...]
    python3 build_playlist.py --protocol protocol.json --check-availability    # pools + finished playlists
    python3 build_playlist.py --protocol protocol.json --prune-unavailable --dry-run   # candidate pools

A successful --plan create does NOT mean the playlist is done -- listen to it
first. If using --exclude-dir, the playlist is deliberately left out of the
exclude-list until you run --finalize on it. Use --show to inspect a live
playlist and --sync to reconcile it to an edited plan.json in the meantime.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import date
from pathlib import Path

from ytm import (
    add_to_exclude_list,
    add_to_exclude_tracks,
    check_vocals,
    UsedTracks,
    format_mmss,
    get_client,
    get_used_tracks,
    is_likely_vocal_title,
    load_exclude_list,
    load_exclude_tracks,
    remove_from_exclude_list,
    resolve_track,
)


DEFAULT_PROTOCOL = {
    "segments": [],
    "total_target_seconds": None,
    "phase_tolerance_seconds": 90,
    "diversity": None,
    "vocal_policy": {"mode": "off"},
    "title_prefix": None,
    "privacy_status": "UNLISTED",
    "description": "Generated by yt-music-playlist skill.",
    "exclude_dir": None,
    "audio_policy": None,
    "candidate_playlists": [],
}

# Filled in under a protocol's "audio_policy" block; a threshold set to None
# turns that check off. See references/audio-analysis.md.
AUDIO_POLICY_DEFAULTS = {
    "voice_flag_frac": 0.35,
    "max_loudness_rise_lu": None,
    "max_arousal_jump": None,
    "max_tempo_ratio": None,
    "min_bpm_confidence": 1.5,
    "arc_metric": "arousal",
    "arc_tolerance": 1.0,
    "arc_min_correlation": 0.3,
    "playback_normalization_lufs": -14.0,
}

BLOCKING_MARKERS = ("NOT FOUND", "ALREADY USED", "DUPLICATE", "TOTAL", "STARTS AT/AFTER BOUNDARY", "HAS VOCALS")


def load_protocol(path: str | None) -> dict:
    """Load a protocol config, filling in defaults for any missing top-level
    keys (including a default-off vocal_policy) so callers never need to
    guard against absent keys."""
    protocol = dict(DEFAULT_PROTOCOL)
    protocol["vocal_policy"] = dict(DEFAULT_PROTOCOL["vocal_policy"])
    if path:
        loaded = json.loads(Path(path).read_text())
        protocol.update({k: v for k, v in loaded.items() if k != "vocal_policy"})
        if "vocal_policy" in loaded:
            protocol["vocal_policy"].update(loaded["vocal_policy"])
    if protocol.get("audio_policy") is not None:
        protocol["audio_policy"] = {**AUDIO_POLICY_DEFAULTS, **protocol["audio_policy"]}
    return protocol


def resolve_exclude_dir(cli_value: str | None, protocol: dict, protocol_path: str | None) -> str | None:
    """Pick the effective exclude-dir: --exclude-dir on the command line wins;
    otherwise fall back to the protocol's "exclude_dir", if any; otherwise
    None (no-reuse tracking stays off).

    A protocol's exclude_dir may use "~" or env vars, and if it's still a
    relative path after expanding those, it's resolved against the
    protocol file's own directory (not the current working directory) so a
    consumer's protocol.json can point at a sibling path portably.
    """
    if cli_value:
        return os.path.expanduser(os.path.expandvars(cli_value))

    raw = protocol.get("exclude_dir")
    if not raw:
        return None
    expanded = os.path.expanduser(os.path.expandvars(raw))
    if not os.path.isabs(expanded) and protocol_path:
        expanded = os.path.join(os.path.dirname(os.path.abspath(protocol_path)), expanded)
    return expanded


def blocking_issues(issues: list[str]) -> list[str]:
    return [i for i in issues if any(m in i for m in BLOCKING_MARKERS)]


def cmd_list_playlists(client) -> int:
    playlists = client.get_library_playlists(limit=None)
    print(json.dumps(
        [{"playlistId": p["playlistId"], "title": p["title"], "count": p.get("count")} for p in playlists],
        indent=2, ensure_ascii=False,
    ))
    return 0


def cmd_add_exclude(client, exclude_dir: str, playlist_ids: list[str]) -> int:
    for pid in playlist_ids:
        playlist = client.get_playlist(pid, limit=1)
        name = playlist.get("title", pid)
        add_to_exclude_list(exclude_dir, pid, name)
        print(f"Added to exclude-list: {pid} ({name!r})")
    return 0


def cmd_remove_exclude(exclude_dir: str, playlist_ids: list[str]) -> int:
    remaining = remove_from_exclude_list(exclude_dir, playlist_ids)
    print(f"Removed (if present): {', '.join(playlist_ids)}")
    print(f"{len(remaining)} entries remain in the exclude-list.")
    return 0


def cmd_add_exclude_track(client, exclude_dir: str, queries: list[str]) -> int:
    for q in queries:
        track = resolve_track(client, q)
        if track is None:
            print(f"NOT FOUND (not added): {q!r}")
            continue
        name = f"{track['artist']} - {track['title']}"
        add_to_exclude_tracks(exclude_dir, track["videoId"], name, track.get("duration_seconds"))
        print(f"Added to track exclude-list: {track['videoId']} ({name!r})")
    return 0


def cmd_list_exclude_tracks(exclude_dir: str) -> int:
    print(json.dumps(load_exclude_tracks(exclude_dir), indent=2, ensure_ascii=False))
    return 0


def _add_items_with_retry(client, playlist_id: str, video_ids: list[str], attempts: int = 3) -> None:
    """add_playlist_items can transiently 409 immediately after create_playlist
    (observed empirically); retry with backoff rather than surfacing a spurious
    failure on an otherwise-fine playlist."""
    last_exc: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            client.add_playlist_items(playlist_id, videoIds=video_ids, duplicates=True)
            return
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            if attempt < attempts:
                time.sleep(2 * attempt)
    raise last_exc


def _in_vocal_exception_slot(track: dict, last_track: dict, vocal_policy: dict) -> bool:
    exception_after = vocal_policy.get("exception_after_seconds")
    return (
        vocal_policy.get("exception_slot") == "last" and exception_after is not None
        and track is last_track and (track["start_seconds"] or 0) >= exception_after
    )


def _apply_vocal_checks(
    client,
    resolved_phases: list[dict],
    issues: list[str],
    check_lyrics: bool,
    vocal_ok_queries: set[str],
    vocal_policy: dict,
) -> None:
    """Enforce a protocol's vocal policy across the whole resolved playlist.

    vocal_policy: {"mode": "off" | "flag" | "block",
                   "exception_after_seconds": int | None,
                   "exception_slot": "last" | None}
    "off" skips all vocal work. "block" treats confirmed lyrics as a hard
    block (unless the track is in the allowed exception slot, or the query
    is manually cleared via the plan's "vocal_ok" list); "flag" reports the
    same signals as advisory-only, never blocking.
    """
    mode = vocal_policy.get("mode", "off")
    if mode == "off":
        return

    exception_after = vocal_policy.get("exception_after_seconds")

    all_tracks = [(phase, track) for phase in resolved_phases for track in phase["tracks"]]
    if not all_tracks:
        return
    last_track = all_tracks[-1][1]

    for phase, track in all_tracks:
        label = f"{track['artist']} - {track['title']!r} at {format_mmss(track['start_seconds'])}"
        override = track.get("query") in vocal_ok_queries
        allowed_vocal_slot = _in_vocal_exception_slot(track, last_track, vocal_policy)

        has_lyrics = check_vocals(client, track["videoId"]) if check_lyrics and track["videoId"] else None

        if has_lyrics is True:
            if override:
                issues.append(f"[{phase['name']}] vocal_ok override (confirmed lyrics ignored): {label}")
            elif allowed_vocal_slot:
                issues.append(f"[{phase['name']}] vocal closer (allowed, starts >= {format_mmss(exception_after)}): {label}")
            elif mode == "block":
                issues.append(f"[{phase['name']}] HAS VOCALS (instrumental rule): {label}")
            else:  # flag
                issues.append(f"[{phase['name']}] vocals detected (advisory): {label}")
        elif has_lyrics is None and check_lyrics:
            issues.append(f"[{phase['name']}] could not verify lyrics (advisory): {label}")

        if is_likely_vocal_title(track) and has_lyrics is not True and not override:
            note = "likely vocal (title)" if allowed_vocal_slot else "likely vocal (title) -- verify before use"
            issues.append(f"[{phase['name']}] {note}: {label}")


def _apply_audio_checks(
    resolved_phases: list[dict],
    issues: list[str],
    segment_configs: dict[str, dict],
    vocal_ok_queries: set[str],
    vocal_policy: dict,
    audio_policy: dict,
) -> None:
    """Analyze every resolved track's audio (cache-first) and add advisory
    issues: audible voice, abrupt transitions, and segments whose intensity
    arc runs against the protocol's per-segment "arc". Attaches each track's
    features as track["audio"] for the timeline. Never produces a blocking
    issue -- these are listening aids, not rules."""
    from audio import FeatureSource, audio_unavailable_reason, load_voice_verdicts, transition

    all_tracks = [(phase, track) for phase in resolved_phases for track in phase["tracks"]]
    if not all_tracks:
        return
    source = FeatureSource()
    misses = {t["videoId"] for _, t in all_tracks if not _cached(t["videoId"])}
    # Cached features need no audio dependencies, so a missing install only
    # costs the uncached tracks.
    reason = audio_unavailable_reason() if misses else None
    if reason:
        issues.append(f"{reason}; {len(misses)} uncached track(s) left unanalyzed")
    elif misses:
        print(f"Analyzing audio for {len(misses)} uncached track(s) (~15s each)...", file=sys.stderr)
    for phase, track in all_tracks:
        if reason and track["videoId"] in misses:
            track["audio"] = None
            continue
        feats, err = source.get(track["videoId"], f"{track['artist']} - {track['title']}")
        track["audio"] = feats
        if err:
            issues.append(f"[{phase['name']}] audio unanalyzed ({err}): {_label(track)}")

    last_track = all_tracks[-1][1]
    voice_frac = audio_policy.get("voice_flag_frac")
    verdicts = load_voice_verdicts()
    if voice_frac is not None:
        for phase, track in all_tracks:
            feats = track["audio"]
            verdict = (verdicts.get(track["videoId"]) or {}).get("verdict")
            if (track.get("query") in vocal_ok_queries or verdict == "ok"
                    or _in_vocal_exception_slot(track, last_track, vocal_policy)):
                continue
            url = f"https://www.youtube.com/watch?v={track['videoId']}"
            if verdict == "salient":
                issues.append(f"[{phase['name']}] voice (you marked it salient): {_label(track)} {url}")
            elif feats and feats["voice_frac"] >= voice_frac:
                segs = feats.get("voice_segments") or []
                when = ", ".join(f"{format_mmss(x)}-{format_mmss(y)}" for x, y in segs[:4]) + (" ..." if len(segs) > 4 else "")
                where = f" at {when}" if segs else ""
                issues.append(f"[{phase['name']}] possible voice in audio ({feats['voice_frac']:.0%} of track{where}; "
                              f"listen, then record with analyze_tracks.py --mark-voice): {_label(track)} "
                              f"{url}&t={segs[0][0] if segs else 0}s")

    max_loud = audio_policy.get("max_loudness_rise_lu")
    max_arousal = audio_policy.get("max_arousal_jump")
    max_tempo = audio_policy.get("max_tempo_ratio")
    for (pa, a), (pb, b) in zip(all_tracks, all_tracks[1:]):
        if not a["audio"] or not b["audio"]:
            continue
        t = transition(a["audio"], b["audio"], audio_policy.get("playback_normalization_lufs"),
                       audio_policy.get("min_bpm_confidence") or 0)
        where = pb["name"] if pa is pb else f"{pa['name']}->{pb['name']}"
        pair = f"at {format_mmss(b['start_seconds'])}: {a['artist']} - {a['title']!r} -> {_label(b, at=False)}"
        if max_loud is not None and t["loudness_rise_lu"] is not None and t["loudness_rise_lu"] > max_loud:
            issues.append(f"[{where}] opens {t['loudness_rise_lu']:+.1f} LU louder than the previous track {pair}")
        if max_arousal is not None and abs(t["arousal_delta"]) > max_arousal:
            issues.append(f"[{where}] energy jump (arousal {t['arousal_delta']:+.1f}) {pair}")
        if max_tempo is not None and t["tempo_ratio"] is not None and t["tempo_ratio"] > max_tempo:
            issues.append(f"[{where}] tempo jump (x{t['tempo_ratio']:.2f}) {pair}")

    metric = audio_policy.get("arc_metric") or "arousal"
    tolerance = audio_policy.get("arc_tolerance") or 0
    min_corr = audio_policy.get("arc_min_correlation")
    for phase in resolved_phases:
        arc = (segment_configs.get(phase["name"]) or {}).get("arc")
        tracks = [t for t in phase["tracks"] if t.get("audio") and t["audio"].get(metric) is not None]
        if arc not in ("rising", "falling") or len(tracks) < 2:
            continue
        sign = 1 if arc == "rising" else -1
        for a, b in zip(tracks, tracks[1:]):
            step = (b["audio"][metric] - a["audio"][metric]) * sign
            if step < -tolerance:
                issues.append(
                    f"[{phase['name']}] arc should be {arc}, but {metric} goes {a['audio'][metric]:.1f} -> "
                    f"{b['audio'][metric]:.1f} at {format_mmss(b['start_seconds'])}: "
                    f"{a['artist']} - {a['title']!r} -> {_label(b, at=False)}")
        values = [t["audio"][metric] for t in tracks]
        corr = _rank_correlation(values) * sign
        if min_corr is not None and len(values) >= 3 and corr < min_corr:
            issues.append(f"[{phase['name']}] arc should be {arc} overall, but {metric} barely follows it "
                          f"(trend {corr:+.2f} < {min_corr}): {', '.join(f'{v:.1f}' for v in values)}")


def _rank_correlation(values: list[float]) -> float:
    """Spearman correlation of values against their order (+1 = steadily
    rising, -1 = steadily falling). Tolerates the dips a gradual arc has."""
    n = len(values)
    if n < 2:
        return 0.0
    order = sorted(range(n), key=lambda i: values[i])
    ranks = [0] * n
    for rank, i in enumerate(order):
        ranks[i] = rank
    mean = (n - 1) / 2
    cov = sum((i - mean) * (r - mean) for i, r in enumerate(ranks))
    var = sum((i - mean) ** 2 for i in range(n))
    return cov / var


def _cached(video_id: str) -> bool:
    from audio import cached_features

    return cached_features(video_id) is not None


def _label(track: dict, at: bool = True) -> str:
    label = f"{track['artist']} - {track['title']!r}"
    return f"{label} at {format_mmss(track['start_seconds'])}" if at else label


def _where_used(track: dict, entry: dict) -> str:
    """Say which used track a match came from, when it isn't obvious."""
    other = "" if entry["videoId"] == track["videoId"] else f"same recording as {entry['label']!r} "
    return f" ({other}{'on' if entry['source'] == 'track exclude-list' else 'in'} {entry['source']})"


def build_timeline(
    client,
    plan: dict,
    protocol: dict,
    exclude_dir: str | None = None,
    check_lyrics: bool = True,
    used: UsedTracks | None = None,
    check_audio: bool = True,
) -> tuple[list[dict], list[str]]:
    """Resolve every track in the plan against a protocol. Returns
    (resolved_phases, issues).

    Each track gets a cumulative "start_seconds" (its position from the top
    of the playlist, not just its own duration). If the protocol sets
    total_target_seconds, that doubles as the grand-total minimum and the
    hard "no track may start at/after this" boundary; content past it is
    otherwise unconstrained.

    used defaults to every excluded playlist/track under exclude_dir, fetched
    live, or nothing if exclude_dir is None (no-reuse tracking is opt-in).
    Pass it explicitly (e.g. with a playlist's own tracks taken out) when
    validating an edit to a playlist that is itself already excluded, as
    --sync does. Tracks match by videoId or by recording (ytm.UsedTracks), so
    another upload of a used track is caught too.
    """
    if used is None:
        used = get_used_tracks(client, exclude_dir) if exclude_dir else UsedTracks()
    in_plan = UsedTracks()
    segments = protocol.get("segments") or []
    has_fixed_segments = bool(segments)
    segment_configs = {s["name"]: s for s in segments}
    total_target = protocol.get("total_target_seconds")
    tolerance = protocol.get("phase_tolerance_seconds") or 0
    diversity = protocol.get("diversity")

    resolved_phases = []
    issues: list[str] = []
    artist_counts: dict[str, int] = {}
    cumulative = 0

    plan_phases = plan.get("phases") or plan.get("segments") or []
    for phase_plan in plan_phases:
        name = phase_plan["name"]
        seg_cfg = segment_configs.get(name)
        if has_fixed_segments and seg_cfg is None:
            issues.append(f"unknown phase name {name!r}; expected one of {list(segment_configs)}")
        target = phase_plan.get("target_seconds", (seg_cfg or {}).get("target_seconds"))
        diversity_exempt = bool((seg_cfg or {}).get("diversity_exempt"))
        count_to_boundary_only = bool((seg_cfg or {}).get("count_to_boundary_only"))
        phase_start = cumulative

        resolved_tracks = []
        prev_artist = None
        for query in phase_plan.get("tracks", []):
            track = resolve_track(client, query)
            if track is None:
                issues.append(f"[{name}] NOT FOUND: {query!r}")
                continue
            identity = (track["videoId"], track["artist"], track["title"], track["duration_seconds"])
            hit = used.match(*identity)
            if hit and hit[0] == "same":
                issues.append(f"[{name}] ALREADY USED (skipped): {_label(track, at=False)}{_where_used(track, hit[1])}")
                continue
            if hit:
                issues.append(
                    f"[{name}] possible other version of a used track (length {format_mmss(track['duration_seconds'])} "
                    f"vs {format_mmss(hit[1]['duration_seconds'])}; listen): {_label(track, at=False)}"
                    f"{_where_used(track, hit[1])}")
            dup = in_plan.match(*identity)
            if dup and dup[0] == "same":
                issues.append(f"[{name}] DUPLICATE in plan (skipped): {_label(track, at=False)} "
                              f"(same recording as {dup[1]['label']!r} in {dup[1]['source']})")
                continue
            in_plan.add_track(track, source=name)

            artist = track["artist"]
            if diversity and not diversity_exempt:
                max_per_artist = diversity.get("max_tracks_per_artist")
                no_consecutive = diversity.get("no_consecutive_same_artist", True)
                if no_consecutive and artist == prev_artist:
                    issues.append(f"[{name}] consecutive same-artist tracks: {artist!r}")
                artist_counts[artist] = artist_counts.get(artist, 0) + 1
                if max_per_artist and artist_counts[artist] == max_per_artist + 1:
                    issues.append(f"artist {artist!r} exceeds cap of {max_per_artist} tracks/playlist")
            prev_artist = artist

            if total_target is not None and cumulative >= total_target:
                issues.append(
                    f"[{name}] STARTS AT/AFTER BOUNDARY: {track['artist']} - {track['title']!r} "
                    f"starts at {format_mmss(cumulative)} (boundary {format_mmss(total_target)})"
                )

            track["start_seconds"] = cumulative
            resolved_tracks.append(track)
            cumulative += track["duration_seconds"] or 0

        phase_total = sum(t["duration_seconds"] or 0 for t in resolved_tracks)

        if target is not None:
            if count_to_boundary_only and total_target is not None:
                # Content past the boundary is irrelevant to length (e.g. a
                # clinician fades the music out around then regardless of
                # what's queued), so only count the portion of this segment
                # that falls before the boundary -- and only flag a
                # shortfall, never an overflow.
                effective_total = max(0, min(phase_total, total_target - phase_start))
                if effective_total < target - tolerance:
                    issues.append(
                        f"[{name}] duration {format_mmss(effective_total)} (before {format_mmss(total_target)}) "
                        f"is under target {format_mmss(target)} by more than {tolerance}s"
                    )
            elif abs(phase_total - target) > tolerance:
                issues.append(
                    f"[{name}] duration {format_mmss(phase_total)} is off target "
                    f"{format_mmss(target)} by more than {tolerance}s"
                )

        resolved_phases.append({
            "name": name,
            "target_seconds": target,
            "tracks": resolved_tracks,
            "total_seconds": phase_total,
            "start_seconds": phase_start,
        })

    grand_total = cumulative
    if total_target is not None and grand_total < total_target:
        issues.append(
            f"TOTAL {format_mmss(grand_total)} is under the {format_mmss(total_target)} minimum"
        )

    vocal_ok_queries = set(plan.get("vocal_ok", []))
    _apply_vocal_checks(client, resolved_phases, issues, check_lyrics, vocal_ok_queries, protocol["vocal_policy"])
    if check_audio and protocol.get("audio_policy"):
        _apply_audio_checks(resolved_phases, issues, segment_configs, vocal_ok_queries,
                            protocol["vocal_policy"], protocol["audio_policy"])

    return resolved_phases, issues


def print_timeline(resolved_phases: list[dict], issues: list[str]) -> None:
    show_audio = any("audio" in t for p in resolved_phases for t in p["tracks"])
    if show_audio:
        from audio import summary_columns
    print(f"{'Time':>8}  {'Phase':<10} " + (f"{'Audio (see analyze_tracks.py --help)':<67} " if show_audio else "") + "Track")
    rule = "-" * (138 if show_audio else 70)
    print(rule)
    total = 0
    for phase in resolved_phases:
        target_str = format_mmss(phase["target_seconds"]) if phase["target_seconds"] is not None else "n/a"
        print(f"{'':>8}  {'--- ' + phase['name'] + ' ---':<10}"
              f" (target {target_str}, actual {format_mmss(phase['total_seconds'])})")
        for track in phase["tracks"]:
            audio_cols = summary_columns(track.get("audio")) + " " if show_audio else ""
            print(f"{format_mmss(track['start_seconds']):>8}  {phase['name']:<10} {audio_cols}{track['artist']} - {track['title']}"
                  f"  [{format_mmss(track['duration_seconds'])}]")
            total = track["start_seconds"] + (track["duration_seconds"] or 0)
    print(rule)
    print(f"{format_mmss(total):>8}  TOTAL")

    if issues:
        print(f"\n{len(issues)} issue(s):")
        for issue in issues:
            print(f"  - {issue}")
    else:
        print("\nNo issues.")


def cmd_plan(client, plan_path: str, protocol: dict, exclude_dir: str | None, dry_run: bool, check_lyrics: bool = True, check_audio: bool = True) -> int:
    plan = json.loads(Path(plan_path).read_text())
    resolved_phases, issues = build_timeline(client, plan, protocol, exclude_dir=exclude_dir, check_lyrics=check_lyrics, check_audio=check_audio)
    print_timeline(resolved_phases, issues)

    blocking = blocking_issues(issues)
    if blocking:
        print("\nBlocking issues present (missing/reused/vocal tracks, timing violations). "
              "Revise the plan and re-run before creating." if not dry_run else
              "\n(Dry run only shown above; resolve blocking issues before a live create.)")
        if not dry_run:
            return 1

    if dry_run:
        print("\nDry run only -- nothing was created.")
        return 0

    title_prefix = protocol.get("title_prefix") or "YouTube Music Playlist"
    title = plan.get("title") or f"{title_prefix} — {date.today().isoformat()}"
    all_video_ids = [t["videoId"] for phase in resolved_phases for t in phase["tracks"]]

    playlist_id = client.create_playlist(
        title=title,
        description=protocol.get("description") or "Generated by yt-music-playlist skill.",
        privacy_status=protocol.get("privacy_status") or "UNLISTED",
    )
    _add_items_with_retry(client, playlist_id, all_video_ids)

    print(f"\nCreated playlist: {title}")
    print(f"URL: https://music.youtube.com/playlist?list={playlist_id}")
    print(f"({len(all_video_ids)} tracks added.)")
    print("\nListen to it, then if you want to edit it:")
    print(f"  python3 build_playlist.py --show {playlist_id}")
    if exclude_dir:
        print(f"  python3 build_playlist.py --exclude-dir {exclude_dir} --sync {playlist_id} --plan {plan_path} --dry-run   # after editing the plan")
        print(
            "\nNOT yet finalized -- its tracks can still be reused elsewhere and it "
            "won't be protected from a future --sync overwrite by name collision:"
        )
        print(f"  python3 build_playlist.py --exclude-dir {exclude_dir} --finalize {playlist_id}   # once you confirm it's done")
    else:
        print(f"  python3 build_playlist.py --sync {playlist_id} --plan {plan_path} --dry-run   # after editing the plan")
    return 0


def cmd_show(client, playlist_id: str) -> int:
    playlist = client.get_playlist(playlist_id, limit=None)
    print(f"Title: {playlist.get('title')}")
    print(f"{'Time':>8}  Track")
    print("-" * 90)
    cumulative = 0
    for track in playlist.get("tracks", []):
        artists = track.get("artists") or []
        artist = artists[0]["name"] if artists else "Unknown"
        duration = track.get("duration_seconds") or 0
        unavailable = "  UNAVAILABLE" if track.get("isAvailable") is False else ""
        print(
            f"{format_mmss(cumulative):>8}  {artist} - {track.get('title')}  [{format_mmss(duration)}]{unavailable}"
            f"  videoId={track.get('videoId')} setVideoId={track.get('setVideoId')}"
        )
        cumulative += duration
    print("-" * 90)
    print(f"{format_mmss(cumulative):>8}  TOTAL")
    return 0


def cmd_sync(client, playlist_id: str, plan_path: str, protocol: dict, exclude_dir: str | None, dry_run: bool, check_lyrics: bool = True, check_audio: bool = True) -> int:
    plan = json.loads(Path(plan_path).read_text())
    current = client.get_playlist(playlist_id, limit=None)
    current_tracks = current.get("tracks", [])
    own_ids = {t["videoId"] for t in current_tracks if t.get("videoId")}
    used = get_used_tracks(client, exclude_dir).without(own_ids) if exclude_dir else UsedTracks()

    resolved_phases, issues = build_timeline(client, plan, protocol, exclude_dir=exclude_dir, check_lyrics=check_lyrics, used=used, check_audio=check_audio)
    print_timeline(resolved_phases, issues)

    blocking = blocking_issues(issues)
    if blocking:
        print("\nBlocking issues present. Revise the plan and re-run before syncing." if not dry_run else
              "\n(Dry run only shown above; resolve blocking issues before a live sync.)")
        if not dry_run:
            return 1

    if dry_run:
        print(f"\nDry run only -- {playlist_id} was not modified.")
        return 0

    removable = [
        {"videoId": t["videoId"], "setVideoId": t["setVideoId"]}
        for t in current_tracks
        if t.get("videoId") and t.get("setVideoId")
    ]
    if removable:
        client.remove_playlist_items(playlist_id, removable)

    all_video_ids = [t["videoId"] for phase in resolved_phases for t in phase["tracks"]]
    _add_items_with_retry(client, playlist_id, all_video_ids)

    print(f"\nSynced {playlist_id}: replaced {len(removable)} track(s) with {len(all_video_ids)} from the plan.")
    if exclude_dir:
        print("Still not finalized -- run --finalize once you confirm it's done.")
    return 0


def _unavailable_tracks(playlist: dict) -> list[dict]:
    """Tracks YouTube Music marks unplayable (removed, region-blocked, etc.)."""
    return [t for t in playlist.get("tracks", []) if t.get("isAvailable") is False]


def _track_name(track: dict) -> str:
    artists = track.get("artists") or []
    return f"{artists[0]['name'] if artists else 'Unknown'} - {track.get('title')}"


def _read_playlist(client, playlist_id: str) -> dict | None:
    try:
        return client.get_playlist(playlist_id, limit=None)
    except Exception as exc:  # noqa: BLE001 - one bad id shouldn't abort the rest
        print(f"  warning: could not fetch playlist {playlist_id!r}: {exc}", file=sys.stderr)
        return None


def default_availability_targets(protocol: dict, exclude_dir: str | None) -> tuple[list[str], list[str]]:
    """(candidate pool ids, finished playlist ids) a protocol cares about:
    its "candidate_playlists" and, with no-reuse tracking on, the
    exclude-list's finished playlists."""
    pools = [p["id"] for p in protocol.get("candidate_playlists") or []]
    finished = [e["id"] for e in load_exclude_list(exclude_dir)] if exclude_dir else []
    return pools, [f for f in finished if f not in pools]


def cmd_check_availability(client, pool_ids: list[str], other_ids: list[str]) -> int:
    """Report unavailable tracks. Candidate pools are prune targets;
    anything else (e.g. a finished session) needs its tracks replaced."""
    found = unreadable = 0
    for pid, is_pool in [(p, True) for p in pool_ids] + [(p, False) for p in other_ids]:
        playlist = _read_playlist(client, pid)
        if playlist is None:
            unreadable += 1
            continue
        bad = _unavailable_tracks(playlist)
        found += len(bad)
        if not bad:
            continue
        kind = "candidate pool -- prune with --prune-unavailable" if is_pool else "needs replacement"
        print(f"{playlist.get('title')} ({pid}) [{kind}]:")
        for t in bad:
            print(f"  UNAVAILABLE: {_track_name(t)}  videoId={t.get('videoId')}")
    print(f"{found} unavailable track(s) across {len(pool_ids) + len(other_ids)} playlist(s)."
          + (f" {unreadable} couldn't be read." if unreadable else ""))
    return 2 if unreadable else 0


def cmd_prune_unavailable(client, playlist_ids: list[str], dry_run: bool) -> int:
    removed = unreadable = 0
    for pid in playlist_ids:
        playlist = _read_playlist(client, pid)
        if playlist is None:
            unreadable += 1
            continue
        bad = [t for t in _unavailable_tracks(playlist) if t.get("videoId") and t.get("setVideoId")]
        for t in bad:
            print(f"{'would remove' if dry_run else 'removing'} from {playlist.get('title')!r}: {_track_name(t)}")
        if bad and not dry_run:
            client.remove_playlist_items(pid, [{"videoId": t["videoId"], "setVideoId": t["setVideoId"]} for t in bad])
            print("  (removals can take several seconds to show up in a re-read of the playlist)")
        removed += len(bad)
    print(f"{removed} unavailable track(s) {'to remove' if dry_run else 'removed'} across {len(playlist_ids)} playlist(s).")
    return 2 if unreadable else 0


def cmd_finalize(client, exclude_dir: str, playlist_id: str) -> int:
    playlist = client.get_playlist(playlist_id, limit=1)
    name = playlist.get("title", playlist_id)
    add_to_exclude_list(exclude_dir, playlist_id, name)
    print(f"Finalized: {playlist_id} ({name!r}) -- its tracks won't be reused in future playlists.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list-playlists", action="store_true", help="list library playlists as JSON, then exit")
    parser.add_argument("--add-exclude", nargs="+", metavar="PLAYLIST_ID", help="finalize playlist id(s) by adding them to the exclude-list, then exit")
    parser.add_argument("--remove-exclude", nargs="+", metavar="PLAYLIST_ID", help="remove playlist id(s) from the exclude-list, then exit")
    parser.add_argument("--add-exclude-track", nargs="+", metavar="QUERY", help='resolve and permanently exclude track(s), e.g. "Artist - Title"')
    parser.add_argument("--list-exclude-tracks", action="store_true", help="print the permanent track exclude-list, then exit")
    parser.add_argument("--exclude-dir", metavar="DIR", help="directory holding this consumer's exclude-playlists.json / exclude-tracks.json; overrides a --protocol's own \"exclude_dir\" if both are given")
    parser.add_argument("--protocol", metavar="PROTOCOL_JSON", help="path to a protocol config (segments, timing, diversity, vocal policy); omit for an unconstrained playlist")
    parser.add_argument("--plan", metavar="PLAN_JSON", help="path to a curated track plan (see module docstring)")
    parser.add_argument("--dry-run", action="store_true", help="resolve and print the timeline, but create/sync nothing")
    parser.add_argument("--no-lyrics-check", action="store_true", help="skip network lyrics lookups (title heuristic still runs); use for fast timing-only iteration")
    parser.add_argument("--no-audio-check", action="store_true", help="skip a protocol's audio_policy analysis (audio columns and advisories); use for fast iteration")
    parser.add_argument("--show", metavar="PLAYLIST_ID", help="print a live playlist's current timeline (with setVideoId), then exit")
    parser.add_argument("--sync", metavar="PLAYLIST_ID", help="reconcile a live, not-yet-finalized playlist to --plan (full replace, in plan order)")
    parser.add_argument("--check-availability", nargs="*", metavar="PLAYLIST_ID", help="report tracks YouTube Music marks unavailable; with no ids, checks the protocol's candidate_playlists plus the exclude-list's finished playlists")
    parser.add_argument("--prune-unavailable", nargs="*", metavar="PLAYLIST_ID", help="remove unavailable tracks (honors --dry-run); with no ids, prunes the protocol's candidate_playlists only")
    parser.add_argument("--finalize", metavar="PLAYLIST_ID", help="record a playlist's tracks as used so they won't be reused in future runs, then exit")
    args = parser.parse_args()

    checking = args.check_availability is not None
    pruning = args.prune_unavailable is not None
    if not any([
        args.list_playlists, args.add_exclude, args.remove_exclude, args.add_exclude_track,
        args.list_exclude_tracks, args.plan, args.show, args.sync, args.finalize, checking, pruning,
    ]):
        parser.error(
            "one of --list-playlists, --add-exclude, --remove-exclude, --add-exclude-track, "
            "--list-exclude-tracks, --plan, --show, --sync, --finalize, --check-availability, "
            "or --prune-unavailable is required"
        )
    if args.sync and not args.plan:
        parser.error("--sync requires --plan")

    protocol = load_protocol(args.protocol)
    exclude_dir = resolve_exclude_dir(args.exclude_dir, protocol, args.protocol)

    needs_exclude_dir = any([
        args.add_exclude, args.remove_exclude, args.add_exclude_track, args.list_exclude_tracks,
        args.finalize,
    ])
    if needs_exclude_dir and not exclude_dir:
        parser.error("no exclude-dir available for this command -- pass --exclude-dir, or use --protocol pointing at a config with its own \"exclude_dir\"")

    client = get_client()

    if args.list_playlists:
        return cmd_list_playlists(client)
    if args.add_exclude:
        return cmd_add_exclude(client, exclude_dir, args.add_exclude)
    if args.remove_exclude:
        return cmd_remove_exclude(exclude_dir, args.remove_exclude)
    if args.add_exclude_track:
        return cmd_add_exclude_track(client, exclude_dir, args.add_exclude_track)
    if args.list_exclude_tracks:
        return cmd_list_exclude_tracks(exclude_dir)
    if checking:
        if args.check_availability:
            return cmd_check_availability(client, [], args.check_availability)
        pools, finished = default_availability_targets(protocol, exclude_dir)
        if not pools and not finished:
            parser.error("--check-availability without ids needs a --protocol with candidate_playlists and/or an exclude-dir")
        return cmd_check_availability(client, pools, finished)
    if pruning:
        ids = args.prune_unavailable or [p["id"] for p in protocol.get("candidate_playlists") or []]
        if not ids:
            parser.error("--prune-unavailable without ids needs a --protocol with candidate_playlists")
        return cmd_prune_unavailable(client, ids, args.dry_run)
    if args.show:
        return cmd_show(client, args.show)
    if args.sync:
        return cmd_sync(client, args.sync, args.plan, protocol, exclude_dir, args.dry_run, check_lyrics=not args.no_lyrics_check, check_audio=not args.no_audio_check)
    if args.finalize:
        return cmd_finalize(client, exclude_dir, args.finalize)
    return cmd_plan(client, args.plan, protocol, exclude_dir, args.dry_run, check_lyrics=not args.no_lyrics_check, check_audio=not args.no_audio_check)


if __name__ == "__main__":
    sys.exit(main())
